# Generated by Django 4.0.2 on 2022-07-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=40)),
                ('precio_servicio', models.FloatField()),
                ('calidad_servicio', models.CharField(max_length=40)),
                ('descripcion_producto', models.CharField(max_length=500)),
            ],
        ),
    ]
