# Generated by Django 4.0.2 on 2022-07-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio_servicio',
            field=models.IntegerField(),
        ),
    ]
