# Generated by Django 4.0.4 on 2022-07-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('autor', models.CharField(max_length=40)),
                ('mensaje', models.CharField(max_length=500)),
                ('comentario', models.CharField(max_length=500)),
            ],
        ),
    ]
