# Generated by Django 4.0.2 on 2022-07-05 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='comentario',
        ),
    ]
